// CRIA TABELA Accounts
CREATE TABLE Accounts (
  id VARCHAR(30) NOT NULL PRIMARY KEY,
  balance FLOAT NOT NULL 
);

// CRIA TABELA Users
CREATE TABLE Users (
 id VARCHAR(30) NOT NULL PRIMARY KEY,
 username VARCHAR(30) UNIQUE NOT NULL,
 password VARCHAR(300) NOT NULL,
 accountId VARCHAR(30) NOT NULL,
 salt VARCHAR(300) NOT NULL,
 CONSTRAINT fk_accounts 
 FOREIGN KEY (accountId) 
 REFERENCES Accounts (id)
 ON DELETE CASCADE
 ON UPDATE CASCADE
);
